
### Send Emails 
POST http://localhost:3000/api/email/send
Content-Type: application/json

{
  "mailOptions":{
    "from":"no-reply@deuslovult.cl",
    "to":"deus@google.com",
    "subject": "Esto es un correo de test",
    "html": "<h1> Hola Deus </h1>"
  },
  "smtpConfig":{
    "host":"sandbox.smtp.mailtrap.io",
    "port":2525,
    "secure": false,
    "auth":{
      "user":"01c99287e41e8f",
      "pass":"48b2c7d60180bc"
    }
  }
}
